from enum import Enum, IntEnum, auto

class InstrGroupTy(IntEnum):
    RV32I = 0
    RV32M = auto()
    RV32A = auto()

# https://github.com/llvm-mirror/llvm/blob/master/lib/Target/RISCV/RISCVInstrFormats.td
class InstrFormatTy(IntEnum):
    InstFormatR = 0
    # InstFormatU = auto()
    # InstFormatI = auto()
    InstFormatJ = auto()
    # InstFormatB = auto()
    # InstFormatS = auto()

class InstrNameTy(IntEnum):
    # RV32I instructions
    LUI = 0
    AUIPC = auto()
    JAL = auto()
    JALR = auto()
    BEQ = auto()
    BNE = auto()
    BLT = auto()
    BGE = auto()
    BLTU = auto()
    BGEU = auto()
    LB = auto()
    LH = auto()
    LW = auto()
    LBU = auto()
    LHU = auto()
    SB = auto()
    SH = auto()
    SW = auto()
    ADDI = auto()
    SLTI = auto()
    SLTIU = auto()
    XORI = auto()
    ORI = auto()
    ANDI = auto()
    SLLI = auto()
    SRLI = auto()
    SRAI = auto()
    ADD = auto()
    SUB = auto()
    SLL = auto()
    SLT = auto()
    SLTU = auto()
    XOR = auto()
    SRL = auto()
    SRA = auto()
    OR = auto()
    AND = auto()
    NOP = auto()
    ECALL = auto()
    EBREAK = auto()

# https://github.com/llvm-mirror/llvm/blob/master/lib/Target/RISCV/RISCVRegisterInfo.td
class RegTy(IntEnum):
    X0 = 0
    X1 = auto()
    X2 = auto()
    X3 = auto()
    X4 = auto()
    X5 = auto()
    X6 = auto()
    X7 = auto()
    X8 = auto()
    X9 = auto()
    X10 = auto()
    X11 = auto()
    X12 = auto()
    X13 = auto()
    X14 = auto()
    X15 = auto()
    X16 = auto()
    X17 = auto()
    X18 = auto()
    X19 = auto()
    X20 = auto()
    X21 = auto()
    X22 = auto()
    X23 = auto()
    X24 = auto()
    X25 = auto()
    X26 = auto()
    X27 = auto()
    X28 = auto()
    X29 = auto()
    X30 = auto()
    X31 = auto()
